version: "2.3"
services:
  ecommerce-develop:
    container_name: ecommerce-develop
    entrypoint: dockerize -template ./.docker/.env.template:.env yarn dev .env
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "./node_modules:/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_ENV=development
      - REACT_APP_SOCKET_HOST=https://corebiz-test.herokuapp.com/api/v1
