version: "2.3"
services:
  ecommerce-develop:
    container_name: eCommerce-develop
    entrypoint: dockerize -template ./.docker/.env.template:.env
    tty: true
    build:
      context: ./.docker
      dockerfile: Dockerfile
    volumes:
        - ".:/app"
        - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_ENV=development
      - REACT_APP_SOCKET_HOST=https://corebiz-test.herokuapp.com/api/v1
